#!/bin/zsh
set -o pipefail
set -e

CURRENT_DIR="$ALGO/bytetools"
source "$CURRENT_DIR/byte-com"

# When press ctrl+c, it will call `trap_ctrlc`.
trap "trap_ctrlc" 2

debug=true
log=true
target="$1"
if [[ "$2" == "0" ]]; then debug=false; fi
if [[ "$3" == "0" ]]; then log=false; fi

test_cnt="$(ls *.in | wc -l)"
seq "$test_cnt" 100 | env_parallel rm -f "$i.out" "$i.res"
rm -f "*.correct"

total_cnt=0
# for i in `ls *.in | sort -g`; do
test_case() {
  i=$1
  std_err="${i%.in}"_std_err
  # Print input samples
  print_color '^' "XY ${i%.in}"
  # full_line '-'
  if [[ $debug == true || $log == true ]]; then
    print_stdout "$i" "false"
  fi

  # run: .inp --> .out
  # dif: .out --> .rel
  out="${i%.in}".res
  rel="${i%.in}".out
  if [[ $debug == true ]]; then
    # Kill(9) after TIME_LIMITS seconds past.
    cmd="$timeout -s9 $TIME_LIMITS ./$target <$i >$out 2>$std_err"
  else
    cmd="$timeout -s9 $TIME_LIMITS time ./$target <$i >$out 2>$std_err"
  fi

  if ! { bash -c "$cmd"; }; then
    error_split '-' "run error"
    print_stdout $std_err
    # rm -rf $std_err
    full_error_line '-'
    error "Run Error, Might exceed the ($TIME_LIMITS)s limit or other issues."
    exit 1
  fi

  if [[ $debug == true ]]; then
    print_split '-' "debug"
    print_stdout $std_err
  fi

  if [[ $debug == true || $log == true ]]; then
    print_split '-' "output"
    cat "$out"
  fi

  if [[ $debug == false ]]; then
    print_split '-' "time"
    print_stdout $std_err
    rm -rf $std_err
  fi

  if [[ -e "$rel" ]]; then
    if diff -y "$out" "$rel" >/dev/null 2>&1; then
      touch $i.correct
      pass_right "PASSED"
    else
      error_right "Failed"
      if [[ $log == true ]]; then
        error_split '-' "compare"
        width=$((WIDTH / 2 / 8 + 2))
        byte-diff "$out" "$rel" "$WIDTH" || true
      fi
    fi
  else
    touch $i.correct
    error_right "Custom"
  fi
  if [[ $debug != true ]]; then
    echo -e "\n"
  fi
}
# done
ls *.in | sort -g | env_parallel -k --lb test_case

print_split '=' "done"

total_cnt=$(ls *.in | wc -l)
if { ls *.correct } &>/dev/null 2>&1; then
  correct_cnt=$(ls *.correct | wc -l)
else
  correct_cnt="0"
fi
if [[ $debug == true ]]; then
  if [[ $total_cnt -gt 0 && $correct_cnt -eq $total_cnt ]]; then
    pass "ALL TESTS PASSED."
  else
    error "SOME TESTS FAILED."
  fi
fi

{ rm -f *.correct } &> /dev/null

# Post work to clean up source file for submiting.
if byte-post "$target"; then
  pbcopy < "$target.cl" && pbpaste 2>&1 >/dev/null
fi

