#!/usr/bin/env bash
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$CURRENT_DIR/byte-com"

cnt=1
trap_repl () {
  error "Caught ctrlc $cnt"
  test $cnt -ge 4 && pass "Exiting $prb..." && exit 0
  ((++cnt))
}

trap 'trap_repl' 2

prb="$1"
cmd="make"
if [[ $# > 1 ]]; then
  shift 1
  cmd="make $@"
fi
while true ; do
  clear && tmux clear-history
  ctime=$(date "+%Y-%m-%d %H:%M:%S")
  perl -pi -e "s|.*accepted.*| \* accepted  : $ctime|g" "$prb".cc
  sleep 0.1
  $cmd
  echo -n "Press Enter to continue"
  read newline
done
