#!/usr/bin/env python3
import os
import sys
import copy
import signal
from pathlib import Path
INPUT_SIGN = "nput"
OUTPUT_SIGN = "utput"
INPUT_SUFX = ".in"
OUTPUT_SUFX = ".out"
INPUT_FILE = "tests.in"
customs = []
inputs = []
outputs = []

# TODO(zq7): add a `tag` for each test case so that we can match
# input and output using id.

# Parsing process goes like following..
#--------- raw text --------------
# TODO(zq7): add notes to a test case.
# Note: xxxxx
# input
# 4 1 2
# 1 3
# 1 2
# output
# 8 9
#-------- parsed test ------------
# @test_input: id  --> id.in
# 4 1 2
# 1 3
# 1 2

# @test_output: id --> id.rel
# 8 9
#--------- running time -----------
# cmd < id.in > id.out
# 4 1 2
# 1 3
# 1 2

# diff id.out id.rel

def is_plain_text(texts):
  return INPUT_SIGN in texts and OUTPUT_SIGN in texts


def write(name, content):
  with open(name, 'w') as f:
    for k, line in enumerate(content):
      if line == "//n":
        f.write("\n")
      else:
        f.write(line + "\n");


def write_two(name, content, nl=''):
  with open(name, 'w') as f:
    for k, v in enumerate(content):
      for line in v:
        f.write(line + nl)
      if k < len(content) - 1:
        f.write("\n")


def write_out():
  cnt = len(customs)
  for k, v in enumerate(customs):
    write(str(k) + INPUT_SUFX, v)

  for k, v in enumerate(inputs):
    write(str(cnt + k) + INPUT_SUFX, v)

  for k, v in enumerate(outputs):
    write(str(cnt + k) + OUTPUT_SUFX, v)

  customs.extend(inputs)
  write_two(INPUT_FILE, customs, nl='\n')


def parse_plain_text(texts):
  inputs_ok = 0
  outputs_ok = 0
  bag = []
  texts = texts.rstrip().split('\n')
  for line in texts:
    if INPUT_SIGN in line or OUTPUT_SIGN in line:
      if inputs_ok:
        inputs.append(copy.deepcopy(bag))

      if outputs_ok:
        outputs.append(copy.deepcopy(bag))
      bag.clear()

    if INPUT_SIGN in line:
      inputs_ok = 1
      outputs_ok = 0

    elif OUTPUT_SIGN in line:
      inputs_ok = 0
      outputs_ok = 1

    else:
      if inputs_ok or outputs_ok:
        bag.append(line.rstrip())

  if len(bag) > 0:
    outputs.append(copy.deepcopy(bag))


def parse_custom(texts):
  bag = []
  texts = texts.rstrip().split('\n')
  for line in texts:
    if INPUT_SUFX in line:
      ok = 1;
    elif line == '':
      if len(bag) > 0 and ok == 0:
        customs.append(copy.deepcopy(bag))
        bag.clear()
    else:
      bag.append(line.rstrip())
  if len(bag) > 0:
    customs.append(copy.deepcopy(bag))


def parse(fn):
  with open(fn, 'r') as f:
    texts = f.read().rstrip().split('\n')
    bag = ""
    for line in texts:
      if line == '':
        if is_plain_text(bag):
          parse_plain_text(bag)
        else:
          parse_custom(bag)
        bag = ""
      else:
        bag += line
        bag += '\n'
    if is_plain_text(bag):
      parse_plain_text(bag)
    else:
      parse_custom(bag)
  write_out()


if __name__ == "__main__":
  if len(sys.argv) < 2:
    print("No file need to parse, exiting..")
    exit(0)
  INPUT_FILE = sys.argv[1]
  with open(INPUT_FILE, 'r') as f:
    texts = f.read()
    if "输入" in texts:
      INPUT_SIGN = "输入"
      OUTPUT_SIGN = "输出"
  parse(sys.argv[1])

