#!/usr/bin/env bash
set -o pipefail
set -e

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$CURRENT_DIR/byte-com"

# When press ctrl+c, it will call `trap_ctrlc`.
trap "trap_ctrlc" 2

debug=true
target="$1"
inputs="$(ls *.inp | sort -g)"
if [[ "$2" == "0" ]]; then debug=false; fi

test_cnt="$(ls *.inp | wc -l)"
for i in $(seq "$test_cnt" 100); do
  rm -f "$i.out"
  rm -f "$i.rel"
done

total_cnt=0
correct_cnt=0
for i in $inputs; do
  # Print input samples
  print_split '=' "${i%.inp}"
  # full_line '-'
  print_stdout "$i"

  # run: .inp --> .out
  # dif: .out --> .rel
  out="${i%.inp}".out
  rel="${i%.inp}".rel
  if [[ $debug == true ]]; then
    cmd="$timeout -s2 $TIME_LIMITS ./$target < $i >$out 2>std_err"
  else
    cmd="$timeout -s2 $TIME_LIMITS time ./$target < $i >$out 2>std_err"
  fi

  if ! { bash -c "$cmd"; }; then
    error_split '-' "run error"
    print_stdout std_err
    rm -rf std_err
    full_error_line '-'
    error "Run Error, Might exceed the ($TIME_LIMITS)s limit or other issues."
    exit 1
  fi

  if [[ $debug == true ]]; then
    print_split '-' "debug"
    print_stdout std_err
    rm -rf std_err
    print_split '-' "output"
    cat "$out"
  fi

  if [[ $debug == false ]]; then
    print_split '-' "time"
    print_stdout std_err
    rm -rf std_err
  fi

  if [[ $debug == true ]]; then
    total_cnt=$((total_cnt + 1))
    if [[ -e "$rel" ]]; then
      if diff -y "$out" "$rel" >/dev/null 2>&1; then
        correct_cnt=$((correct_cnt + 1))
        pass_right "PASSED"
      else
        error_right "Failed"
        error_split '-' "compare"
        diff -y -W $WIDTH "$out" "$rel" || true
      fi
    else
      correct_cnt=$((correct_cnt + 1))
      error_right "Custom"
    fi
  fi
done

print_split '=' "done"

if [[ $debug == true ]]; then
  if [[ $total_cnt -gt 0 && $correct_cnt -eq $total_cnt ]]; then
    pass "ALL TESTS PASSED."
  else
    error "SOME TESTS FAILED."
  fi
fi

