#!/usr/bin/env bash

# set -xep

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$CURRENT_DIR/byte-com"

elf=$1
cnt=$2
with_compare=$3

run_test() {
  # echo "Generating..."
  ./"$elf"_ge > $i.gg
  #--------------------------------------
  # echo "Running..."
  cmd=""$timeout" -s2 "$TIME_LIMITS" ./"$elf" < $i.gg > $i.ga 2>run_err"
  if ! { bash -c "$cmd"; }; then
    error "\n----------------Run Error---------------------------\n"
    cat run_err
    error "\n-----------------------------------------------------\n"
    # cat $i.gg | tee -a $elf.in
    exit 1
  fi
  #--------------------------------------
  if [[ "$with_compare" == "1" ]]; then
    # echo "Comparing..."
    cmd="./"$elf"_mp < $i.gg > $i.gb 2>compare_error"
    if ! { bash -c "$cmd"; }; then
      error "\n---------------Compare Error------------------------------\n"
      cat compare_error
      error "\n----------------------------------------------------------\n"
      exit 1
    fi
    if ! diff -y -W 60 "$i.ga" "$i.gb" 2>&1 >/dev/null; then
      error "\n----------Different input---------------"
      cat $i.gg
      error "\n------------Output------------------------"
      diff -y -W 60 "$i.ga" "$i.gb"
      # cat $i.gg | tee -a $elf.in
      exit 1
    fi
  fi
  printf "test...$i \e[1;32m\\t\\t\\t PASS\e[m\n"
}

clean () {
  rm -f *.gg *.ga *.gb
  rm -f compare_error
  rm -f run_err
}

clean
for i in $(seq 1 "$cnt"); do
  (run_test) &
  if (( $i % 4 == 0 )); then wait; fi
done
clean
