#!/usr/bin/env bash

var=1

function trap_ctrlc () {
  echo [1m[31mCaught ctrlc $var[0m
  test $var -ge 10 && exit 124
  var=$(expr $var + 1)
}

if [[ "$1" == "run" ]]; then
  cmd="make run"
elif [[ "$1" == "comp" ]]; then
  cmd='make MKFLAG_RELEASE=1 comp'
elif [[ "$1" == "release" ]]; then
  rm -f $(basename $(PWD))
  cmd='make MKFLAG_RELEASE=1'
else
  cmd="make test"
fi

trap 'trap_ctrlc' 2
filename=$2

# Ref: https://stackoverflow.com/questions/12771909/bash-using-trap-ctrlc
while [ 1 ]; do
  clear && tmux clear-history
  trap 'trap_ctrlc' 2
  if [[ ! -z "$filename" && "$filename" != "release" ]]; then
    ctime=$(date "+%Y-%m-%d %H:%M:%S")
    perl -pi -e "s|.*accepted.*| \* accepted  : $ctime|g" "$filename".cc
  fi
  sleep 0.1
  $cmd
  echo -en Press Enter to continue
  read newline
done
