#!/usr/bin/env bash
set -e

# BYTETOOLS sepcifies where this reop located.
BYTETOOLS="$ALGO/bytetools"
EDITOR="subl"

if [[ -z "$ALGO" ]]; then
  echo "Expected ALGO environment to be set."
  exit 1
fi

if [[ -z "$BYTETOOLS" ]]; then
  echo "Expected BYTETOOLS environment to be set."
  exit 1
fi

PWD=$(basename $PWD)
GEN_SRC="$PWD.ge"
CMP_SRC="$PWD.mp"
GEN_TEM="$BYTETOOLS/gen.cc"
PRB_TEM="$BYTETOOLS/template.cc"
PRB_MKF="$BYTETOOLS/Makefile"

if [[ "$1" == "-m" ]]; then
  # byte-sketch -m problem
  PRB_TEM="$BYTETOOLS/template-kickstart.cc"
  shift
elif [[ "$1" == "gen" ]]; then
  cat "$GEN_TEM" > "$GEN_SRC"
  $EDITOR "$GEN_SRC"
  exit 0
elif [[ "$1" == "cmp" ]]; then
  prb=$(basename "$problem")
  ctime=$(date "+%Y-%m-%d %H:%M:%S")
  sed -e "s/\\\$NAME/$prb/g" \
      -e "s/\\\$DATE/$ctime/g" \
      "$PRB_TEM" > "$CMP_SRC"
	$EDITOR "$CMP_SRC"
	exit 0
fi

problem="$*"
if test -d $problem; then
  echo "==> Problem $problem already exists."
  exit 1
elif [[ "$problem" == "test" ]]; then
  echo "==> Can't create problem with name [test], cause of make cyclic rule."
  exit 1
fi

mkdir -p $problem
prb=$(basename "$problem")
ctime=$(date "+%Y-%m-%d %H:%M:%S")
sed -e "s/\\\$NAME/$prb/g" \
    -e "s/\\\$DATE/$ctime/g" \
    "$PRB_TEM" > "$problem/$prb.cc"

cp "$PRB_MKF" "$problem/Makefile"

echo "==> Problem $problem created."

cd $problem
inp="$prb.ii"
src="$prb.cc"
touch "$inp" && echo "null" > "$inp"
$EDITOR "$inp"
# Sleep for a while so that the sublime plugin can work
# to put the newly created file at the most right tab.
sleep 0.1
$EDITOR "$src"
byte-repl $prb
